service: users-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: dev
  region: us-east-1
  timeout: 15
functions:
  hello:
    handler: handler.users_api
